name: Node Express GraphQL Template CI

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop

jobs:
  build_and_test:
    name: Build & Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup environment
        uses: actions/setup-node@v2
        with:
          cache: 'yarn'
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        run: yarn install
      - name: Lint
        run: yarn lint
      - name: Test
        run: yarn test
      - name: Build
        run: yarn build:local
      - name: Jest coverage report
        uses: ArtiomTr/jest-coverage-report-action@v2.1.1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          package-manager: yarn
          threshold: ${{steps.threshold.outputs.prop}}
          skip-step: all
          annotations: all
      - uses: codecov/codecov-action@v2
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          verbose: true
          files: ./reports/test-report.xml
